Online/Online/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Online/pages/urls.py
from django.urls import path, include
from . import views

app_name = 'pages'
urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.books, name='books'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('addbook/', views.addbook, name='addbook'),
    path('updateuser/', views.updateUser, name='updateuser'),
    path('logout/', views.logout, name='logout'),
    path('extendbook/<slug:slug>', views.extendbook, name="extend"),
    path('bookdetails/<slug:slug>', views.bookdetails, name='bookdetails'),
    path('updatebook/<slug:slug>', views.updatebook, name='updatebook'),
    path('borrow/<slug:slug>', views.borrow, name="borrow"),
    path('returnbook/<slug:slug>', views.returnbook, name="return"),
]

Online/pages/templates/parts/adminnav.html
<input type="checkbox" id="check">
   <!-- Navbar -->
   <div id='Navigate'>
   <nav  class="main-header navbar navbar-expand navbar-white navbar-light" id='navg'>      
   <!--sidebar button-->
    <label class="sidebarlabel" for="check">
      <i class="fas fa-bars" id="sidebar-btn"></i>
    </label>
   <label class="logo">University Library</label>
</nav>
</div>

<!--Side bar-->
<div class="sidebar">
  <a href="{% url 'pages:index' %}"><label class="sidebartitle">Home</label></a>
  <a href="{% url 'pages:updateuser' %}" class="sidebarlinks" ><span>Profile</span></a>
  <a href="{% url 'pages:books' %}" class="sidebarlinks"><span>Books</span></a>
  <a href="{% url 'pages:addbook' %}" class="sidebarlinks"><span>Add Book</span></a>
   
  <a href="{% url 'pages:logout' %}" class="sidebarlinks" ><span>Log out</span></a>
</div>

Online/pages/templates/parts/indexnavbar.html
  <!-- Navbar -->
  <input type="checkbox" id="check">
   <div id='Navigate'>
   <nav  class="main-header navbar navbar-expand navbar-white navbar-light" id='navg'>      
   <!--sidebar button-->
    <label class="sidebarlabel" for="check">
      <i class="fas fa-bars" id="sidebar-btn"></i>
    </label>
   <label class="logo">University Library</label>
    <!-- Left navbar links -->
    <ul class="navbar-nav">
    <!-- <li class="nav-item">
      </li>-->
      <li class="nav-item d-none d-sm-inline-block"> 
       <li><a href="{% url 'pages:index'%}" class="nav-link" id = 'NavA'>Home</a></li> 
       <li><a href="{% url 'pages:books'%}" class="nav-link" id = 'NavA'>Books</a></li> 
       {% if not user.is_authenticated %}
       <li><a href="{% url 'pages:login'%}" class="nav-link" id = 'NavA'>Login</a></li> 
       <li><a href="{% url 'pages:signup'%}" class="nav-link" id = 'NavA'>Sign up</a></li> 
       {% endif %}
       <li><a href="#" class="nav-link" id = 'NavA'>About us</a></li> 
    </ul>
</nav>
</div>

<!--Side bar-->
<div class="sidebar">
  <a href="{% url 'pages:index'%}"><label class="sidebartitle">Home</label></a>
   {% if not user.is_authenticated %}
  <a href="{% url 'pages:login'%}" class="sidebarlinks" ><span>Sign in</span></a>
  <a href="{% url 'pages:signup'%}" class="sidebarlinks"><span>Sign up</span></a>
   {% endif %}
  <a href="{% url 'pages:books'%}" class="sidebarlinks"><span>Books</span></a>
</div>

Online/pages/templates/parts/loggednav.html
<input type="checkbox" id="check">
   <!-- Navbar -->
   <div id='Navigate'>
   <nav  class="main-header navbar navbar-expand navbar-white navbar-light" id='navg'>      
   <!--sidebar button-->
    <label class="sidebarlabel" for="check">
      <i class="fas fa-bars" id="sidebar-btn"></i>
    </label>
   <label class="logo">University Library</label>
    
</nav>
</div>
<!--Side bar-->
<div class="sidebar">
  <a href="{% url 'pages:index' %}"><label class="sidebartitle">Home</label></a>
    {% if user.is_authenticated %}
  <a href="{% url 'pages:updateuser' %}" class="sidebarlinks" ><span>Profile</span></a>
   {% endif %}
  <a href="{% url 'pages:books' %}"  class="sidebarlinks"><span>Books</span></a>
  {% if user.is_authenticated %}
    <a href="{% url 'pages:logout' %}"  class="sidebarlinks"><span>Log out</span></a>
  {% endif %}
</div>