Online/Online/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Online/pages/urls.py
from django.urls import path, include
from . import views

app_name = 'pages'
urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.books, name='books'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('addbook/', views.addbook, name='addbook'),
    path('updateuser/', views.updateUser, name='updateuser'),
    path('logout/', views.logout, name='logout'),
    path('extendbook/<slug:slug>', views.extendbook, name="extend"),
    path('bookdetails/<slug:slug>', views.bookdetails, name='bookdetails'),
    path('updatebook/<slug:slug>', views.updatebook, name='updatebook'),
    path('borrow/<slug:slug>', views.borrow, name="borrow"),
    path('returnbook/<slug:slug>', views.returnbook, name="return"),
]

Online/pages/templates/base.html
{% block head %}

{% endblock head %}
 
<body style="overflow-x: hidden">

{% block content %}



{% endblock content %}

<!--footer-->

   <div id='test'>
   <footer class="footer">
     <div class="footer-left">
         <img src="" alt="">
         <p>University Library Website is where you can find your desired books and gain knwoledge day by day.  </p>
     </div>

      <ul class="footer-right">

       <li>
          <h2>Majors</h2>
          <ul class="box">
            <li><a href="#">Engineering</a></li>
            <li><a href="#">Computer Sciene</a></li>
            <li><a href="#">Mass Communication</a></li>
            <li><a href="#">Medicine</a></li>
            <li><a href="#">Science</a></li>
          </ul>
       </li>

       <li class = "Additional">
        <h2>Useful Links</h2>
        <ul class="box">
          <li><a href="https://github.com/">GitHub</a></li>
          <li><a href="https://www.w3schools.com/">W3schools</a></li>
          <li><a href="https://www.linkedin.com/">LinkedIn</a></li>
          <li><a href="https://www.geeksforgeeks.org/">GeeksforGeeks</a></li>
          <li><a href="https://www.tutorialspoint.com/">TutorialsPoint</a></li>
        </ul>
     </li>


     <li>
      <h2>Address</h2>
      <ul class="box">
        <li><a href="#">5 Dr. Ahmed Zewail Street</a></li>
        <li><a href="#">Dokki</a></li>
        <li><a href="#">Giza</a></li>
        <li><a href="#">Egypt</a></li>
       
      </ul>
    </li>
  </ul>

  <div class='footer-bottom'>
    <p>All Rights Reserved by &copy;conceptial 2021</p>
  </div>

   </footer>
</div>

  </body>
</html>

Online/pages/templates/bookdetails.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<!-- Required meta tags -->
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta charset="utf-8">
  <!-- Bootstrap CSS -->
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
      <!--Fonts-->
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500&display=swap" rel="stylesheet">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" >
    <!--Css-->
     <link rel="stylesheet" href= "{% static 'css/BookDetails.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <title>University Library</title>
    <script>
        function Borrow() {
        var xhttp = new XMLHttpRequest();
        const container = document.getElementById('container');
        xhttp.onreadystatechange = function() {
          if (this.readyState == 4 && this.status == 200) {
            document.getElementById("container").innerHTML =
            this.response;
          }
        };
        xhttp.open("GET", "{% url 'pages:borrow' book_details.slug %}", true);
        xhttp.send();
      }

      function Return() {
        var xhttp = new XMLHttpRequest();
        const container = document.getElementById('container');
        xhttp.onreadystatechange = function() {
          if (this.readyState == 4 && this.status == 200) {
            document.getElementById("container").innerHTML =
            this.response;
          }
        };
        xhttp.open("GET", "{% url 'pages:return' book_details.slug %}", true);
        xhttp.send();
      }
      function Extend() {
        var xhttp = new XMLHttpRequest();
        const container = document.getElementById('container');
        xhttp.onreadystatechange = function() {
          if (this.readyState == 4 && this.status == 200) {
            document.getElementById("container").innerHTML =
            this.response;
          }
        };
        xhttp.open("GET", "{% url 'pages:extend' book_details.slug %}", true);
        xhttp.send();
      }
    </script>
  </head>
 
 
{% endblock head %}
{% block content %}

{% if user.is_authenticated and user.is_superuser %}
   {% include 'parts/adminnav.html' %}
{% elif  user.is_authenticated and not user.is_superuser%}
    {% include 'parts/loggednav.html' %}
{% else %}
    {% include 'parts/indexnavbar.html' %}
{% endif %} 

<!--Update form-->
<div class="cont">
    <form method ='GET'>
       {%csrf_token %}
      <div class="title">Book details</div>
        <div class="user-details">
            <div class="input-box">
                <span class="details">Title</span>
               <div class='info'> {{book_details.title}}</div>
            </div>
            <div class="input-box">
              <span class="details">Author Name</span>
              <div class='info'>{{book_details.author}}</div> 
          </div>
          <div class="input-box">
              <span class="details">ISBN</span>
              <div class='info'>{{book_details.isbn}}</div> 
          </div>
          <div class="input-box">
              <span class="details">Publication Year</span>
              <div class='info'>{{book_details.publication_year}}</div> 
              
          </div>
          <div class="input-box">
              <span class="details">Borrowing Period</span>
              <div class='info'>{{book_details.borrowing_period}} days</div> 
          </div>
          <div class="input-box">
              <span class="details">Status</span>
              <div class='info' id="status">{{book_details.status}}</div> 
          </div>
          {% if user.is_authenticated and user.is_superuser %}
            <a class="btn" href="{% url 'pages:updatebook' book_details.slug %}" >Update</a>
            <button class="btn1" id="borrow" onclick="Borrow()" type="button">Borrow</button>
            <button class="btn1" id="return" onclick="Return()" type="button">Return</button>
            <button class="btn1" id="extend"  onclick="Extend()" type="button">Extend</button>
          {% elif  user.is_authenticated and not user.is_superuser  %}
            <button class="btn1" id="borrow" onclick="Borrow()" type="button">Borrow</button>
            <button class="btn1" id="return" onclick="Return()" type="button">Return</button>
            <button class="btn1" id="extend"  onclick="Extend()" type="button">Extend</button>
          {% endif %}

          </div>
 
    </form>
  </div>
 <center><div id="container"></div></center>
  

{% endblock content %}

Online/pages/templates/books.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<head>
    <!-- Required meta tags -->
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta charset="utf-8">
    <!-- Bootstrap CSS -->
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
      <!--Fonts-->
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500&display=swap" rel="stylesheet">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" >
    <!--Css-->
     <link rel="stylesheet" href= "{% static 'css/book.css' %}">
    <script src= "{% static 'js/index.js' %}" defer></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <title>University Library</title>
  </head>
{% endblock head %}

{% block content %}
 
{% if user.is_authenticated and user.is_superuser %}
   {% include 'parts/adminnav.html' %}
{% elif  user.is_authenticated and not user.is_superuser%}
    {% include 'parts/loggednav.html' %}
{% else %}
    {% include 'parts/indexnavbar.html' %}
{% endif %} 

<!--search-->

<section id="search">
   <div class="SearchBar">
    <form class="example" method='POST'> 
    {% csrf_token %}
      <select name="category">
        {% for cat in category %} 
        <option value="{{cat.name}}" id = "opt">{{cat.name}}</option>
         {% endfor %}
      </select>
      <input type="text" placeholder="What are you looking for?" name="search">
      <button type="submit" class="searchbutton"></i>Search</button>
    </form>
  </div>  
</section>
   

<section class="view">
    <div id="dd">
        <h2  id ="ab">Books</h2>
     </div>
     {% for book in books %}
     <div class="b-container">
         <div class="book">
             <div class="b-content">
                 <p class="p">
                     <span class="btitle"> Book Tiltle: </span> 
                     <span class="binfo">{{book.title}}</span> 
                 </p>
                 <p class="p">
                    <span class="btitle">Book ISBN: </span>  
                    <span class="binfo">{{book.isbn}}</span>
                </p>
                <p class="p">
                    <span class="btitle">Book Author:</span>   
                    <span class="binfo">{{book.author}}</span>
                 </p>
                 <p class="p">
                    <span class="btitle">Book Status:</span>   
                    <span class="binfo">{{book.status}}</span>
                 </p>
                 <a class="btn" href="{% url 'pages:bookdetails' book.slug %}" >Details</a>
         </div>
       </div>
     </div>
 {% endfor %}
</section>


{% endblock content %}

Online/pages/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta charset="utf-8">
  <!-- Bootstrap CSS -->
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
      <!--Fonts-->
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500&display=swap" rel="stylesheet">     
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" >
    <!--Css-->
     <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <script src="{% static 'js/index.js'%}"  defer></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <title>University Library</title>
  </head>
  
{% endblock head %}



{% block content %}


{% if user.is_authenticated and user.is_superuser %}
   {% include 'parts/adminnav.html' %}
{% elif  user.is_authenticated and not user.is_superuser%}
    {% include 'parts/loggednav.html' %}
{% else %}
    {% include 'parts/indexnavbar.html' %}
{% endif %}

<body>
    <!-- home section -->
    <div id="home" class="parallax-section" style="text-align: center">
        <div class="parallax-section"></div>
        <div class="group center" style="text-align: center">
            <h1 id ='h1' style="text-align: center">University Library</h1>
        <br>
        {% if not user.is_authenticated%}
            <a href="{% url 'pages:login'%}" class="btn btn-primary" id='Log'>  Log in </a>
        {% endif %}
        </div>
    </div>

    <!-- gallery section -->
    <section id="gallery">

    <div class="container">
      <div class="mySlides">
        <div class="numbertext">1 / 6</div>
        <img src="{% static 'img/g1.jpg' %}"  style="width:100%">
      </div>

      <div class="mySlides">
        <div class="numbertext">2 / 6</div>
        <img src="{% static 'img/g2.jpg' %}"  style="width:100%">
      </div>

  <div class="mySlides">
    <div class="numbertext">3 / 6</div>
    <img src= "{% static 'img/g3.jpg' %}"  style="width:100%">
  </div>

  <div class="mySlides">
    <div class="numbertext">4 / 6</div>
    <img src=  "{% static 'img/g4.jpg' %}"   style="width:100%">
  </div>

  <div class="mySlides">
    <div class="numbertext">5 / 6</div>
    <img src= "{% static 'img/g7.jpg' %}"  style="width:100%">
  </div>

  <div class="mySlides">
    <div class="numbertext">6 / 6</div>
    <img src= "{% static 'img/g6.jpg' %}" style="width:100%">
  </div>


  <a class="prev" onclick="plusSlides(-1)">❮</a>
  <a class="next" onclick="plusSlides(1)">❯</a>

      <div class="caption-container">
        <p id="caption"></p>
      </div>

    <div class="row">
            <div class="column">
                <img class="demo cursor" src= "{% static 'img/g1.jpg' %}"  style="width:100%" onclick="currentSlide(1)">
            </div>
            <div class="column">
                <img class="demo cursor" src= "{% static 'img/g2.jpg' %}"  style="width:100%" onclick="currentSlide(2)">
            </div>
            <div class="column">
                <img class="demo cursor" src= "{% static 'img/g3.jpg' %}" style="width:100%" onclick="currentSlide(3)">
            </div>
            <div class="column">
                <img class="demo cursor" src="{% static 'img/g4.jpg' %}"  style="width:100%" onclick="currentSlide(4)">
            </div>
            <div class="column">
                <img class="demo cursor" src="{% static 'img/g7.jpg' %}"  style="width:100%" onclick="currentSlide(5)">
            </div>
            <div class="column">
                <img class="demo cursor" src="{% static  'img/g6.jpg' %}" style="width:100%" onclick="currentSlide(6)">
            </div>
        </div>
    </div>
  </section>


    <br>

    <br>
<!-- instructions section -->
<section id="instructions">
	<h3 id="inst">Instructions</h3>
	<div id='ins'>
    <ul>
      <li><p> Carry your student ID card (or CHOIS Card) with you when you enter the library.</p></li>
      <li><p>Do not take any book or other library material out of the library without following the borrowing procedures.</p></li>
      <li><p>Make sure to return the borrowed items by the due date.</p></li>
      <li><p> In case any of the borrowed items being lost, damaged, or destroyed, you are required to replace the lost /damaged/destroyed item with a new one.</p></li>
      <li><p>Never write in books or cut pages out of them.</p></li>
      <li><p>Return books/materials to their original location on the bookshelf.</p></li>
      <li><p> Any food is not allowed to have in the library. Only drink bottles with a cap that could be tightly closed are permitted in the reading room.</p></li>
      <li><p>Using of mobile phones is prohibited. Switch your mobile phone off and keep it in your bag, etc. while you are in the library.</p></li>
      <li><p> Private conversations are not permitted. Even talking in a whisper or standing and chatting may be disturbing to others. Strictly prohibited from doing the above.</p></li>
      <li><p> Refrain from leaving your baggage, etc. on library chairs/sofas, and avoid taking up two seats by sitting on one and putting your baggage, clothes, etc. on the other.Also, please be sure not to leave valuables unattended.</p></li>
    </ul>
	</div>
</section>
{% endblock content %}

Online/pages/templates/login.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}
{% block head %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta charset="utf-8">
  <!-- Bootstrap CSS -->
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
      <!--Fonts-->
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500&display=swap" rel="stylesheet">
    <!--Css-->
     <link rel="stylesheet" href= "{% static 'css/Login.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <title>University Library</title>
  </head>
{% endblock head %}

{% block content %}



<!--Login Form-->
    <div class="cont">
      <form method="POST">
      {% csrf_token %}
      {% if not user.is_authenticated %}
        <div class="title">Login</div>
          <div class="user-details">
              
              <div class="input-box">
                <span class="details">Username</span>
                <span>{{form.username}}</span> 
            </div>
            <div class="input-box">
                <span class="details">Password</span>
                <span>{{form.password}}</span>
            </div> 
          </div>
          <div class="Rebutton">
              <input type="submit" value="Log In" >
          </div>
          <div class="form-text" style="font-size: 20px; color: white">
                  Don't have an account? <a href="{% url 'pages:signup' %}">Register Now</a>
              </div>
          {% elif user.is_authenticated%}
          <div class="input-box">
           <center ><span class="details" id="warn">You're Already logged in!</span>
           <p>Do you want to log out?</p>
           <a href="{% url 'pages:logout'%}" id="err" class="btn btn-primary" >  Log out </a>
          </center> 
        </div> 
      
          {% endif %}
      </form>
      
      
    </div>
    
{% endblock content %}

Online/pages/templates/signup.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}
{% block head %}
<!--suppress ALL -->
    <head>
    <!-- Required meta tags -->
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta charset="utf-8">
  <!-- Bootstrap CSS -->
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
      <!--Fonts-->
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500&display=swap" rel="stylesheet">
    <!--Css-->
     <link rel="stylesheet" href= "{% static 'css/Signup.css' %}">
     <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <!--<script src="{% static 'js/student.js' %}"></script> -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <title>University Library</title>
  <script type="text/javascript">
  $(function(){
     $("#fnwarning").hide()
     $("#lnwarning").hide()
     $("#unwarning").hide()
     $("#emwarning").hide()
     $("#p1warning").hide()
     $("#p2warning").hide()
     
     var fname_error = false;
     var lname_error = false;
     var uname_error = false;
     var email_error = false;
     var p1_error = false;
     var p2_error = false;

     $("#first_name_input_field").focusout(function(){
          check_fname();
     })

     $("#last_name_input_field").focusout(function(){
        check_lname();
      })

      $("#email_input_field").focusout(function(){
         check_email();
      })

      $("#password1_input_field").focusout(function(){
         check_p1();
      })

      $("#password2_input_field").focusout(function(){
        check_p2();
      })
 
      function check_fname(){
        var pattern = /^[a-zA-Z]*$/;
        var fname = $("#first_name_input_field").val();
        if (pattern.test(fname) && fname != '')
        {
          $("#fnwarning").hide();
          $("#first_name_input_field").css("border-bottome", "2px solid #34F458")
        } else{
          $("#fnwarning").html("First Name should contain only characters")
          $("#fnwarning").show();
          $("#first_name_input_field").css("border-bottome", "2px solid #F90A0A")
          fname_error = true;
        }
      }

      function check_lname(){
        var pattern = /^[a-zA-Z]*$/;
        var lname = $("#last_name_input_field").val();
        if (pattern.test(lname) && lname != '')
        {
          $("#lnwarning").hide();
          $("#last_name_input_field").css("border-bottome", "2px solid #34F458")
        } else{
          $("#lnwarning").html("Last Name should contain only characters")
          $("#lnwarning").show();
          $("#last_name_input_field").css("border-bottome", "2px solid #F90A0A")
          fname_error = true;
        }
      }

      function check_p1(){
        var number = /([0-9])/;
        var  alphabets = /([a-zA-Z])/;
        var special_characters = /([~,!,@,#,$,%,^,&,*,-,_,+,=,?,>,<])/;
        var password_length = $("#password1_input_field").val().length;
        if (password_length < 8)
        {
          $("#p1warning").html("Password should be at least 8 characters")
          $("#p1warning").show();
          $("#password1_input_field").css("border-bottome", "2px solid #F90A0A")
          p1_error = true;
        }
        else{
          if($('#password1_input_field').val.match(number)  && $('#password1_input_field').val().match(alphabets) && $('#password1_input_field').val().match(special_characters)){

          }else{
            $("#p1warning").html("Password should include alphabets, numbers and special characters.")
            $("#p1warning").show();
            $("#password1_input_field").css("border-bottome", "2px solid #F90A0A")
            p1_error = true;
          }
        }
      }

      function check_p2(){
        var password1 = $("#password1_input_field").val();
        var password2 = $("#password2_input_field").val();
        if (password1 !== password2 )
        {
          $("#p2warning").html("Passwords Did not Matched")
          $("#p2warning").show();
          $("#password1_input_field").css("border-bottome", "2px solid #F90A0A")
          p2_error = true;
        }else {
               $("#p2warning").hide();
               $("#password1_input_field").css("border-bottom","2px solid #34F458");
            }
      }

        function check_email() {
            var pattern = /^([\w-\.]+@([\w-]+\.)+[\w-]{2,4})?$/;
            var email = $("#email_input_field").val();
            if (pattern.test(email) && email !== '') {
               $("#emwarning").hide();
               $("#email_input_field").css("border-bottom","2px solid #34F458");
            } else {
               $("#emwarning").html("Invalid Email");
               $("#emwarning").show();
               $("#form_email").css("border-bottom","2px solid #F90A0A");
               email_error = true;
            }
         }

         $("#registration_form").submit(function() {
            fname_error = false;
            lname_error = false;
            email_error = false;
            p1_error = false;
            p2_error = false;

            check_fname();
            check_lname();
            check_email();
            check_p1();
            check_p2();

            if (fname_error === false && lname_error === false && email_error === false && p1_error === false && p2_error === false) {
               alert("Registration Successfull");
               return true;
            } else {
               alert("Please Fill the form Correctly");
               return false;
            }
          });

     
        });        
  

  </script>
  </head>
{% endblock head %}

{% block content %}





<!--Sign up form-->
    <div class="cont">
      <form method='POST' id="registration_form" >
       {% csrf_token %}
       {% if not user.is_authenticated %}
        <div class="title">Registration</div>
          <div class="user-details">
       
              <div class="input-box">
                  <span class="details">First Name</span>
                  <div >{{form.first_name}}</div>
                  <span id="fnwarning"></span>
              </div>
               <div class="input-box">
                  <span class="details">Last Name</span>
                 <div > {{form.last_name}}</div>
                 <span id="lnwarning"></span>
              </div>

              <div class="input-box">
                <span class="details">Username</span>
              <div >{{form.username}}</div>
              <span id="unwarning"></span>
            </div>
            <div class="input-box">
                <span class="details">Email</span>
                <div >{{form.email}}</div>
                <span id="emwarning"></span>
            </div>
          
            <div class="input-box">
                <span class="details">Password</span>
                 <div>{{form.password1}}</div>
                 <span id="p1warning"></span>
            </div>
            <div class="input-box">
                <span class="details">Confirm Password</span>
                <div>{{form.password2}}</div>
                <span id="p2warning"></span>
            </div>
             <div class="Rebutton">
              <input type="submit"  value="Sign up">
            </div>
          <div class="form-text" style="color: white; font-size: 20px">
                  Already have an account? <a href="{% url 'pages:login' %}">Sign in</a>
              </div>
          </div>
            {% elif user.is_authenticated%}
            <div class="input-box">
             <center ><span class="details" id="warn">You're Already logged in!</span>
             <p>Do you want to log out?</p>
             <a href="{% url 'pages:logout'%}" id="err" class="btn btn-primary" >  Log out </a>
            </center> 
            </div>

        </div>
            {% endif %}

      </form>
    </div>


{% endblock content %}